# Site settings
title: DHUM 150 Final Project
email: gcelesta@uvic.ca
description: > # this means to ignore newlines until "baseurl:"
    DHUM 150 log website converted to GitHub-based website
baseurl: '' # the subpath of your site, e.g. /blog/

# url is currently only used only for the RSS feed in feed.xml
url: http://gcelesta.github.io

# This can be '' to hide the Github nav button
github: 'gcelesta/github.io'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
